### ISSUE TITLE
SCRF: Notable Works - Bounty

### ISSUE THREAD

**Issue by ghettodev** [smartcontractresearchforum/docs#14]
# SCRF: Notable Works - Bounty

## What is SCRF?

The [Smart Contract Research Forum](https://www.smartcontractresearch.org/) (SCRF) is where academics, researchers, and industry leaders from all over the world come together to discuss research, solicit thoughtful peer review, and find new projects on which to collaborate. You can learn [more about SCRF here](https://github.com/smartcontractresearchforum/docs). 

## Background

The SCRF team employs a series of content types we have designed to help make blockchain research accessible to a wider audience. In our forum, users can find [Research Summaries](https://www.smartcontractresearch.org/tag/summary), [Interviews](https://www.smartcontractresearch.org/tag/interview), [Discussion Posts](https://www.smartcontractresearch.org/tag/discussion), and [Notable Works](https://www.smartcontractresearch.org/tag/notable-works) that researchers have posted. Each type of content acts as an entry point to start a conversation or to educate about a particular topic.

Some content types are considered reference materials like our [Notable Works](https://github.com/smartcontractresearchforum/docs/blob/main/en/content_notable_works.md), which are lists of key readings in each category area, intended to help point researchers to important or fundamental research in the domain being discussed. You can see some examples [in our forum](https://www.smartcontractresearch.org/tag/notable-works).

## What we are looking for

We need writers, researchers, or crypto-enthusiasts with a familiarity with blockchain technologies (e.g. zero knowledge proofs, governance, mechanism design, etc.) to share what they believe are _foundational_ research papers, technical articles, or other materials that apply to any specific category of the forum. Once found, the work should be submitted as a pull request to our repo in the format outlined in the [template](https://github.com/smartcontractresearchforum/docs/blob/main/en/content_notable_works_template.md).

You can see the current list of [Notable Works in our repository](https://github.com/smartcontractresearchforum/docs/blob/main/en/content_notable_works.md).

## Acceptance Criteria

- A high quality, relevant, and foundational research paper, technical article, or other material is submitted as a PR to our [Notable Works](https://github.com/smartcontractresearchforum/docs/blob/main/en/content_notable_works.md) in our repository.
- The submission adheres to the standards outlined in the [template](https://github.com/smartcontractresearchforum/docs/blob/main/en/content_notable_works_template.md)
- The submission is approved by our Research Team as being worthy of inclusion
- If you would like to propose the change in our forum before you submit the PR, please visit the appropriate Notable Works [thread](https://www.smartcontractresearch.org/tag/notable-works) and ask your questions there
- If the work is a research paper, it should include a full citation.

## Resources

**Chat:** We use our [#general chat](https://discord.com/channels/784234332617048065/784234333111451670) for discussions about content, blockchain-related events, coordination, and project planning.

**Project Management:** All the work that SCRF produces is created collaboratively in a [public document pipeline](https://github.com/orgs/smartcontractresearchforum/projects/5). Please feel free to look around, if you have any questions or see something you’d like to help out with, hit us up in [chat](https://discord.com/channels/784234332617048065/784234333111451670)

**Comment by eleventh19** [comment]
meeting from today got rescheduled to next week. going to review the process and figure out the next steps

**Comment by eleventh19** [comment]
I just realized that I accidentally created a duplicate card (#116) but that one is more active so I'm going to close this card out
