### ISSUE TITLE
💼 Job Description

### ISSUE THREAD

**Issue by ttaloute** [smartcontractresearchforum/docs#56]
### JD Vertical

Engagement

### Stage

Request for Discovery

### Link to Doc

https://docs.google.com/document/d/14xB70CFpcbRaIjZVEqBKBrkmFSOIZlaaK447cRBHRqo/edit#heading=h.l899m8k3v6mr

### Next Steps

Review the JD (title and description) and approve for posting on Github

### SCRF Team

@zubepaul @gh

### Approval Date

7/18/2022

**Comment by twan-dev** [comment]
probably send this to the researchers (dubbed "primary authors") we are/have worked with after the requirements are fully developed

**Comment by ralphlombreglia** [comment]
Edited this doc in Suggestion mode, Thursday, July 14, 2022, 2:29:10 PM ET.

**Comment by vsterling** [comment]
[PR 61](https://github.com/smartcontractresearchforum/docs/pull/61) created

**Comment by vsterling** [comment]
The [Content Project Manager](https://github.com/smartcontractresearchforum/docs/blob/main/en/hiring_content_project_manager.md) is now live. (I just created a https://github.com/smartcontractresearchforum/docs/pull/62 to list it to the ReadMe.)

**Comment by vsterling** [comment]
JD added to the [ReadMe](https://github.com/smartcontractresearchforum/docs)

**Comment by vsterling** [comment]
Hey @SirAh0 this issue is closed, but I can't close issues that live in the Docs repo.
